# ???????
excel.strategy.scan.package=exceltool.builder.strategy.impl

# ??????????????????
feishu.credentials=cli_a53a3449003d5013:71wrAp0M1B61v9jeQc7BAc1FKfSss6ea,cli_a53a3bc70459d00e:XZSzwAIH569OrjFVnrjsdgfu8Bc8GJCS

# HTTP????(??)
feishu.http.timeout=30000